# Generated by Django 3.0.5 on 2021-05-20 19:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(help_text='reporter_name', max_length=50)),
                ('reporter_email', models.CharField(help_text='reporter_name', max_length=50)),
                ('reporter_phone_number', models.CharField(help_text='reporter_phone_number', max_length=50)),
                ('bug_description', models.TextField(blank=True, help_text='a short description', max_length=250, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 21, 0, 57, 13, 904547))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 5, 21, 0, 57, 13, 904547))),
                ('status', models.CharField(choices=[('TODO', 'TODO'), ('In Fix', 'In Fix'), ('Resolved', 'Resolved')], default='TODO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BugClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 21, 0, 57, 13, 905544))),
                ('tags', models.CharField(max_length=100)),
                ('bug_report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.BugReport')),
            ],
        ),
    ]
